# Site settings
title: "Brock Whitbread"
email: brock.whitbread@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A portfolio site for Brock "Pan Blanco" Whitbread
baseurl: "/zap-rowsdower.github.io" # the subpath of your site, e.g. /blog/
url: "http://zap-rowsdower.github.io" # the base hostname & protocol for your site
twitter_username: zapRowsdowr
github_username:  zap-rowsdower

# Build settings
markdown: redcarpet
highlighter: pygments
timezone: America/New_York

# Include supported plugins
gems: 
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed
