# Site settings
title: Brock "Pan Blanco" Whitbread
email: brock.whitbread@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A portfolio site for Brock "Pan Blanco" Whitbread
baseurl: "/panblanco/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zapRowsdowr
github_username:  zap-rowsdower

# Build settings
markdown: redcarpet
highlighter: true
timezone: America/New_York

# Include supported plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed